<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Str;
use Illuminate\Support\Carbon;
use App\Models\{
    Role, User, Seller, Category, Product, Cart,
    Order, OrderDetail, Review, Payment, UserAddress
};

class DatabaseSeeder extends Seeder
{
    public function run(): void
    {
        $now = Carbon::now();

        /**
         * 1️⃣ Roles (3 roles)
         */
        Role::insert([
            ['name' => 'admin', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'seller', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'user', 'created_at' => $now, 'updated_at' => $now],
        ]);

        /**
         * 2️⃣ Users (10 users)
         */
        User::insert([
            [
                'name' => 'Admin Sistem',
                'email' => 'admin@example.com',
                'role_id' => 1,
                'password' => Hash::make('password'),
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'Ahmad Seller',
                'email' => 'ahmad@example.com',
                'role_id' => 2,
                'password' => Hash::make('password'),
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'Budi Customer',
                'email' => 'budi@example.com',
                'role_id' => 3,
                'password' => Hash::make('password'),
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'Sari Wijaya',
                'email' => 'sari@example.com',
                'role_id' => 2,
                'password' => Hash::make('password'),
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'Rudi Hartono',
                'email' => 'rudi@example.com',
                'role_id' => 2,
                'password' => Hash::make('password'),
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'Maya Sari',
                'email' => 'maya@example.com',
                'role_id' => 3,
                'password' => Hash::make('password'),
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'Dewi Anggraini',
                'email' => 'dewi@example.com',
                'role_id' => 2,
                'password' => Hash::make('password'),
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'Fajar Pratama',
                'email' => 'fajar@example.com',
                'role_id' => 3,
                'password' => Hash::make('password'),
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'Citra Lestari',
                'email' => 'citra@example.com',
                'role_id' => 2,
                'password' => Hash::make('password'),
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'Hendra Gunawan',
                'email' => 'hendra@example.com',
                'role_id' => 3,
                'password' => Hash::make('password'),
                'created_at' => $now,
                'updated_at' => $now,
            ],
        ]);

        /**
         * 3️⃣ Sellers (10 sellers)
         */
        Seller::insert([
            [
                'user_id' => 2,
                'nama_toko' => 'Toko Elektronik Maju',
                'deskripsi' => 'Menjual berbagai barang elektronik rumah tangga berkualitas.',
                'alamat' => 'Jl. Trans Sulawesi No.45, Majene',
                'no_telp' => '081234567890',
                'latitude' => -3.4321000,
                'longitude' => 119.3332100,
                'foto_toko' => 'toko_elektronik.jpg',
                'status' => 'aktif',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'user_id' => 4,
                'nama_toko' => 'FreshMart Sayur & Buah',
                'deskripsi' => 'Toko yang menyediakan sayur dan buah-buahan segar setiap hari.',
                'alamat' => 'Jl. Jenderal Sudirman No.12, Majene',
                'no_telp' => '081245678901',
                'latitude' => -3.4305000,
                'longitude' => 119.3319000,
                'foto_toko' => 'freshmart.jpg',
                'status' => 'aktif',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'user_id' => 5,
                'nama_toko' => 'Bengkel Motor Sejahtera',
                'deskripsi' => 'Melayani servis ringan, servis berat, dan sparepart motor.',
                'alamat' => 'Jl. Poros Majene-Mamuju No.89',
                'no_telp' => '081256789012',
                'latitude' => -3.4352000,
                'longitude' => 119.3401200,
                'foto_toko' => 'bengkel_motor.jpg',
                'status' => 'aktif',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'user_id' => 7,
                'nama_toko' => 'Butik Fashion Modern',
                'deskripsi' => 'Menjual pakaian trendy dan aksesoris fashion terkini.',
                'alamat' => 'Jl. Ahmad Yani No.33, Majene',
                'no_telp' => '081267890123',
                'latitude' => -3.4289000,
                'longitude' => 119.3298000,
                'foto_toko' => 'butik_fashion.jpg',
                'status' => 'aktif',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'user_id' => 9,
                'nama_toko' => 'Toko Bangunan Makmur',
                'deskripsi' => 'Pusat bahan bangunan lengkap untuk kebutuhan konstruksi.',
                'alamat' => 'Jl. Pahlawan No.77, Majene',
                'no_telp' => '081278901234',
                'latitude' => -3.4337000,
                'longitude' => 119.3356000,
                'foto_toko' => 'toko_bangunan.jpg',
                'status' => 'aktif',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'user_id' => 2,
                'nama_toko' => 'Electronic Center',
                'deskripsi' => 'Spesialis elektronik dan gadget terbaru.',
                'alamat' => 'Jl. Niaga No.21, Majene',
                'no_telp' => '081289012345',
                'latitude' => -3.4318000,
                'longitude' => 119.3322000,
                'foto_toko' => 'electronic_center.jpg',
                'status' => 'aktif',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'user_id' => 4,
                'nama_toko' => 'Organic Food Store',
                'deskripsi' => 'Menyediakan makanan organik dan sehat untuk keluarga.',
                'alamat' => 'Jl. Kesatria No.6, Majene',
                'no_telp' => '081290123456',
                'latitude' => -3.4275000,
                'longitude' => 119.3287000,
                'foto_toko' => 'organic_store.jpg',
                'status' => 'aktif',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'user_id' => 5,
                'nama_toko' => 'Sparepart Motor Lengkap',
                'deskripsi' => 'Toko sparepart motor original dengan harga terjangkau.',
                'alamat' => 'Jl. Veteran No.4, Majene',
                'no_telp' => '081301234567',
                'latitude' => -3.4293000,
                'longitude' => 119.3304000,
                'foto_toko' => 'sparepart_motor.jpg',
                'status' => 'aktif',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'user_id' => 7,
                'nama_toko' => 'Kids Fashion Shop',
                'deskripsi' => 'Pakaian anak-anak berkualitas dengan model lucu.',
                'alamat' => 'Jl. Cendrawasih No.18, Majene',
                'no_telp' => '081312345678',
                'latitude' => -3.4309000,
                'longitude' => 119.3349000,
                'foto_toko' => 'kids_fashion.jpg',
                'status' => 'aktif',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'user_id' => 9,
                'nama_toko' => 'Hardware Store',
                'deskripsi' => 'Alat-alat pertukangan dan perkakas rumah tangga.',
                'alamat' => 'Jl. Pemuda No.27, Majene',
                'no_telp' => '081323456789',
                'latitude' => -3.4268000,
                'longitude' => 119.3276000,
                'foto_toko' => 'hardware_store.jpg',
                'status' => 'aktif',
                'created_at' => $now,
                'updated_at' => $now,
            ],
        ]);

        /**
         * 4️⃣ Categories (10 categories)
         */
        Category::insert([
            [
                'nama_kategori' => 'Elektronik',
                'deskripsi' => 'Produk-produk elektronik seperti TV, kipas angin, dan kulkas.',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'nama_kategori' => 'Fashion',
                'deskripsi' => 'Pakaian dan aksesoris fashion pria dan wanita.',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'nama_kategori' => 'Peralatan Rumah Tangga',
                'deskripsi' => 'Peralatan rumah tangga seperti panci, wajan, sapu, dan ember.',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'nama_kategori' => 'Kesehatan',
                'deskripsi' => 'Produk kesehatan seperti vitamin, suplemen, dan alat kesehatan.',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'nama_kategori' => 'Olahraga',
                'deskripsi' => 'Perlengkapan olahraga seperti sepatu, bola, dan pakaian sport.',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'nama_kategori' => 'Makanan & Minuman',
                'deskripsi' => 'Makanan ringan, minuman, dan kebutuhan dapur lainnya.',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'nama_kategori' => 'Otomotif',
                'deskripsi' => 'Produk otomotif seperti oli, sparepart, dan aksesoris kendaraan.',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'nama_kategori' => 'Mainan Anak',
                'deskripsi' => 'Mainan edukatif dan hiburan untuk anak-anak.',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'nama_kategori' => 'Kecantikan',
                'deskripsi' => 'Produk kecantikan seperti skincare, make-up, dan parfum.',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'nama_kategori' => 'Aksesoris',
                'deskripsi' => 'Aksesoris seperti jam tangan, gelang, tas, dan dompet.',
                'created_at' => $now,
                'updated_at' => $now,
            ],
        ]);

        /**
         * 5️⃣ Products (10 products)
         */
        Product::insert([
            [
                'seller_id' => 1,
                'category_id' => 1,
                'nama_produk' => 'Kipas Angin Cosmos 16 Inch',
                'deskripsi' => 'Kipas angin dengan 3 kecepatan, hemat listrik, garansi 1 tahun.',
                'harga' => 250000.00,
                'stok' => 15,
                'berat' => 3.50,
                'foto' => 'kipas_cosmos.jpg',
                'status' => 'aktif',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'seller_id' => 1,
                'category_id' => 1,
                'nama_produk' => 'LED TV 32 Inch Sharp',
                'deskripsi' => 'TV LED 32 inch dengan resolusi HD dan garansi resmi.',
                'harga' => 1850000.00,
                'stok' => 8,
                'berat' => 5.20,
                'foto' => 'tv_sharp.jpg',
                'status' => 'aktif',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'seller_id' => 2,
                'category_id' => 6,
                'nama_produk' => 'Apel Malang Premium 1kg',
                'deskripsi' => 'Apel segar langsung dari petani Malang, manis dan renyah.',
                'harga' => 35000.00,
                'stok' => 50,
                'berat' => 1.00,
                'foto' => 'apel_malang.jpg',
                'status' => 'aktif',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'seller_id' => 2,
                'category_id' => 6,
                'nama_produk' => 'Jeruk Pontianak 1kg',
                'deskripsi' => 'Jeruk manis tanpa biji, segar dan berkualitas.',
                'harga' => 28000.00,
                'stok' => 40,
                'berat' => 1.00,
                'foto' => 'jeruk_pontianak.jpg',
                'status' => 'aktif',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'seller_id' => 3,
                'category_id' => 7,
                'nama_produk' => 'Oli Motor Matic 10W-40 800ml',
                'deskripsi' => 'Oli berkualitas untuk performa mesin motor matic.',
                'harga' => 45000.00,
                'stok' => 35,
                'berat' => 0.90,
                'foto' => 'oli_motor.jpg',
                'status' => 'aktif',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'seller_id' => 3,
                'category_id' => 7,
                'nama_produk' => 'Ban Motor Tubeless 80/90-14',
                'deskripsi' => 'Ban motor tubeless berkualitas dengan daya cengkeram baik.',
                'harga' => 220000.00,
                'stok' => 20,
                'berat' => 3.50,
                'foto' => 'ban_motor.jpg',
                'status' => 'aktif',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'seller_id' => 4,
                'category_id' => 2,
                'nama_produk' => 'Dress Wanita Casual',
                'deskripsi' => 'Dress casual bahan katun nyaman untuk sehari-hari.',
                'harga' => 120000.00,
                'stok' => 25,
                'berat' => 0.30,
                'foto' => 'dress_wanita.jpg',
                'status' => 'aktif',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'seller_id' => 4,
                'category_id' => 2,
                'nama_produk' => 'Kemeja Pria Lengan Panjang',
                'deskripsi' => 'Kemeja formal bahan oxford cocok untuk kerja.',
                'harga' => 150000.00,
                'stok' => 30,
                'berat' => 0.40,
                'foto' => 'kemeja_pria.jpg',
                'status' => 'aktif',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'seller_id' => 5,
                'category_id' => 3,
                'nama_produk' => 'Set Peralatan Masak 10 Pcs',
                'deskripsi' => 'Set peralatan masak lengkap untuk dapur modern.',
                'harga' => 350000.00,
                'stok' => 15,
                'berat' => 4.50,
                'foto' => 'peralatan_masak.jpg',
                'status' => 'aktif',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'seller_id' => 5,
                'category_id' => 3,
                'nama_produk' => 'Panci Stainless Steel 24cm',
                'deskripsi' => 'Panci stainless steel anti karat dan tahan lama.',
                'harga' => 85000.00,
                'stok' => 40,
                'berat' => 1.20,
                'foto' => 'panci_stainless.jpg',
                'status' => 'aktif',
                'created_at' => $now,
                'updated_at' => $now,
            ],
        ]);

        /**
         * 6️⃣ Carts (10 cart items)
         */
        Cart::insert([
            [
                'user_id' => 3,
                'product_id' => 1,
                'quantity' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'user_id' => 3,
                'product_id' => 3,
                'quantity' => 2,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'user_id' => 6,
                'product_id' => 2,
                'quantity' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'user_id' => 6,
                'product_id' => 7,
                'quantity' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'user_id' => 8,
                'product_id' => 5,
                'quantity' => 3,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'user_id' => 8,
                'product_id' => 6,
                'quantity' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'user_id' => 10,
                'product_id' => 4,
                'quantity' => 5,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'user_id' => 10,
                'product_id' => 8,
                'quantity' => 2,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'user_id' => 3,
                'product_id' => 9,
                'quantity' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'user_id' => 6,
                'product_id' => 10,
                'quantity' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
        ]);


        /**
         * 9️⃣ Reviews (10 reviews)
         */
        Review::insert([
            [
                'product_id' => 1,
                'user_id' => 3,
                'rating' => 5,
                'komentar' => 'Kipas angin berfungsi dengan baik, dingin dan tidak berisik.',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'product_id' => 2,
                'user_id' => 6,
                'rating' => 4,
                'komentar' => 'TV kualitas bagus, pengiriman cepat dan aman.',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'product_id' => 3,
                'user_id' => 3,
                'rating' => 4,
                'komentar' => 'Apel segar dan manis, pengiriman cepat.',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'product_id' => 4,
                'user_id' => 10,
                'rating' => 5,
                'komentar' => 'Jeruknya manis sekali, keluarga suka!',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'product_id' => 5,
                'user_id' => 8,
                'rating' => 3,
                'komentar' => 'Oli standar, harga cukup bersaing.',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'product_id' => 6,
                'user_id' => 8,
                'rating' => 4,
                'komentar' => 'Ban berkualitas, pemasangan cepat.',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'product_id' => 7,
                'user_id' => 6,
                'rating' => 5,
                'komentar' => 'Dressnya bagus, bahan nyaman dipakai.',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'product_id' => 8,
                'user_id' => 10,
                'rating' => 4,
                'komentar' => 'Kemeja cocok untuk kerja, bahan tidak panas.',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'product_id' => 9,
                'user_id' => 3,
                'rating' => 5,
                'komentar' => 'Set peralatan lengkap, kualitas premium.',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'product_id' => 10,
                'user_id' => 6,
                'rating' => 4,
                'komentar' => 'Panci awet dan mudah dibersihkan.',
                'created_at' => $now,
                'updated_at' => $now,
            ],
        ]);

        /**
         * 11️⃣ User Addresses (10 addresses)
         */
        UserAddress::insert([
            [
                'user_id' => 3,
                'nama_penerima' => 'Budi Customer',
                'no_telp' => '081233344455',
                'alamat' => 'Jl. Trans Sulawesi No.88, RT 01/RW 02',
                'provinsi' => 'Sulawesi Barat',
                'kota' => 'Majene',
                'kecamatan' => 'Banggae',
                // 'kelurahan' => 'Banggae',
                'kode_pos' => '91412',
                'is_default' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'user_id' => 3,
                'nama_penerima' => 'Budi Customer',
                'no_telp' => '081233344456',
                'alamat' => 'Jl. Poros Polewali No.22, RT 03/RW 04',
                'provinsi' => 'Sulawesi Barat',
                'kota' => 'Polewali Mandar',
                'kecamatan' => 'Polewali',
                // 'kelurahan' => 'Madate',
                'kode_pos' => '91413',
                'is_default' => false,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'user_id' => 6,
                'nama_penerima' => 'Maya Sari',
                'no_telp' => '081244455566',
                'alamat' => 'Jl. Merdeka No.15, RT 02/RW 03',
                'provinsi' => 'Sulawesi Barat',
                'kota' => 'Majene',
                'kecamatan' => 'Banggae',
                // 'kelurahan' => 'Baurung',
                'kode_pos' => '91412',
                'is_default' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'user_id' => 8,
                'nama_penerima' => 'Fajar Pratama',
                'no_telp' => '081255566677',
                'alamat' => 'Jl. Diponegoro No.45, RT 04/RW 01',
                'provinsi' => 'Sulawesi Barat',
                'kota' => 'Majene',
                'kecamatan' => 'Banggae',
                // 'kelurahan' => 'Lembang',
                'kode_pos' => '91412',
                'is_default' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'user_id' => 10,
                'nama_penerima' => 'Hendra Gunawan',
                'no_telp' => '081266677788',
                'alamat' => 'Jl. Gatot Subroto No.12, RT 05/RW 02',
                'provinsi' => 'Sulawesi Barat',
                'kota' => 'Majene',
                'kecamatan' => 'Banggae',
                // 'kelurahan' => 'Lembang',
                'kode_pos' => '91412',
                'is_default' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'user_id' => 6,
                'nama_penerima' => 'Maya Sari',
                'no_telp' => '081277788899',
                'alamat' => 'Jl. Veteran No.8, RT 03/RW 05',
                'provinsi' => 'Sulawesi Barat',
                'kota' => 'Majene',
                'kecamatan' => 'Banggae',
                // 'kelurahan' => 'Banggae',
                'kode_pos' => '91412',
                'is_default' => false,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'user_id' => 8,
                'nama_penerima' => 'Fajar Pratama',
                'no_telp' => '081288899900',
                'alamat' => 'Jl. Pahlawan No.33, RT 06/RW 04',
                'provinsi' => 'Sulawesi Barat',
                'kota' => 'Majene',
                'kecamatan' => 'Banggae',
                // 'kelurahan' => 'Baurung',
                'kode_pos' => '91412',
                'is_default' => false,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'user_id' => 10,
                'nama_penerima' => 'Hendra Gunawan',
                'no_telp' => '081299900011',
                'alamat' => 'Jl. Ahmad Yani No.27, RT 07/RW 03',
                'provinsi' => 'Sulawesi Barat',
                'kota' => 'Majene',
                'kecamatan' => 'Banggae',
                // 'kelurahan' => 'Lembang',
                'kode_pos' => '91412',
                'is_default' => false,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'user_id' => 3,
                'nama_penerima' => 'Budi Customer',
                'no_telp' => '081300011122',
                'alamat' => 'Jl. Cendrawasih No.19, RT 08/RW 06',
                'provinsi' => 'Sulawesi Barat',
                'kota' => 'Majene',
                'kecamatan' => 'Banggae',
                // 'kelurahan' => 'Baurung',
                'kode_pos' => '91412',
                'is_default' => false,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'user_id' => 6,
                'nama_penerima' => 'Maya Sari',
                'no_telp' => '081311122233',
                'alamat' => 'Jl. Merpati No.5, RT 09/RW 07',
                'provinsi' => 'Sulawesi Barat',
                'kota' => 'Majene',
                'kecamatan' => 'Banggae',
                // 'kelurahan' => 'Banggae',
                'kode_pos' => '91412',
                'is_default' => false,
                'created_at' => $now,
                'updated_at' => $now,
            ],
        ]);
    }
}